application: portfolio
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: portfolio_project/webapp/images/favicon.ico
  upload: portfolio_project/webapp/images/favicon.ico

- url: /static
  static_dir: portfolio_project/static/

- url: /(admin|api).*
  script: main.app

- url: /
  static_files: portfolio_project/webapp/index.html
  upload: portfolio_project/webapp/index.html

- url: /
  static_dir: portfolio_project/webapp/

skip_files:
# Configuration files are sent to the server seperately.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^portfolio_project/sass/.*
- ^portfolio_project/port/.*

libraries:
- name: django
  version: "1.4"


env_variables:
  IS_APP_ENGINE: 'true'
