application: portfolio
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: portfolio_project/static/

- url: .*
  script: main.app

libraries:
- name: django
  version: "1.4"

- name: PIL
  version: "latest"
